// Code generated by go-swagger; DO NOT EDIT.

package relation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// CategorySubCategoryListRelationOKCode is the HTTP code returned for type CategorySubCategoryListRelationOK
const CategorySubCategoryListRelationOKCode int = 200

/*CategorySubCategoryListRelationOK 登录成功，返回登录信息

swagger:response categorySubCategoryListRelationOK
*/
type CategorySubCategoryListRelationOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20035 `json:"body,omitempty"`
}

// NewCategorySubCategoryListRelationOK creates CategorySubCategoryListRelationOK with default headers values
func NewCategorySubCategoryListRelationOK() *CategorySubCategoryListRelationOK {
	return &CategorySubCategoryListRelationOK{}
}

// WithPayload adds the payload to the category sub category list relation o k response
func (o *CategorySubCategoryListRelationOK) WithPayload(payload *models.InlineResponse20035) *CategorySubCategoryListRelationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the category sub category list relation o k response
func (o *CategorySubCategoryListRelationOK) SetPayload(payload *models.InlineResponse20035) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CategorySubCategoryListRelationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrCategorySubCategoryListRelationDefault error

swagger:response categorySubCategoryListRelationDefault
*/
type NrCategorySubCategoryListRelationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrCategorySubCategoryListRelationDefault creates NrCategorySubCategoryListRelationDefault with default headers values
func NewNrCategorySubCategoryListRelationDefault(code int) *NrCategorySubCategoryListRelationDefault {
	if code <= 0 {
		code = 500
	}

	return &NrCategorySubCategoryListRelationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the category sub category list relation default response
func (o *NrCategorySubCategoryListRelationDefault) WithStatusCode(code int) *NrCategorySubCategoryListRelationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the category sub category list relation default response
func (o *NrCategorySubCategoryListRelationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the category sub category list relation default response
func (o *NrCategorySubCategoryListRelationDefault) WithPayload(payload *models.Error) *NrCategorySubCategoryListRelationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the category sub category list relation default response
func (o *NrCategorySubCategoryListRelationDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrCategorySubCategoryListRelationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
