// Code generated by go-swagger; DO NOT EDIT.

package community

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrCommunityDetailHandlerFunc turns a function with the right signature into a community detail handler
type NrCommunityDetailHandlerFunc func(NrCommunityDetailParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrCommunityDetailHandlerFunc) Handle(params NrCommunityDetailParams) middleware.Responder {
	return fn(params)
}

// NrCommunityDetailHandler interface for that can handle valid community detail params
type NrCommunityDetailHandler interface {
	Handle(NrCommunityDetailParams) middleware.Responder
}

// NewNrCommunityDetail creates a new http.Handler for the community detail operation
func NewNrCommunityDetail(ctx *middleware.Context, handler NrCommunityDetailHandler) *NrCommunityDetail {
	return &NrCommunityDetail{Context: ctx, Handler: handler}
}

/*NrCommunityDetail swagger:route GET /community/detail Community communityDetail

圈子详情

圈子详情

*/
type NrCommunityDetail struct {
	Context *middleware.Context
	Handler NrCommunityDetailHandler
}

func (o *NrCommunityDetail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrCommunityDetailParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
