// Code generated by go-swagger; DO NOT EDIT.

package msg

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// MsgDetailHandlerFunc turns a function with the right signature into a msg detail handler
type MsgDetailHandlerFunc func(MsgDetailParams) middleware.Responder

// Handle executing the request and returning a response
func (fn MsgDetailHandlerFunc) Handle(params MsgDetailParams) middleware.Responder {
	return fn(params)
}

// MsgDetailHandler interface for that can handle valid msg detail params
type MsgDetailHandler interface {
	Handle(MsgDetailParams) middleware.Responder
}

// NewMsgDetail creates a new http.Handler for the msg detail operation
func NewMsgDetail(ctx *middleware.Context, handler MsgDetailHandler) *MsgDetail {
	return &MsgDetail{Context: ctx, Handler: handler}
}

/*MsgDetail swagger:route GET /msg/detail Msg msgDetail

Msg详情

Msg详情

*/
type MsgDetail struct {
	Context *middleware.Context
	Handler MsgDetailHandler
}

func (o *MsgDetail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewMsgDetailParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
