// Code generated by go-swagger; DO NOT EDIT.

package msg

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// MsgUnsendListOKCode is the HTTP code returned for type MsgUnsendListOK
const MsgUnsendListOKCode int = 200

/*MsgUnsendListOK 已发送消息列表

swagger:response msgUnsendListOK
*/
type MsgUnsendListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20026 `json:"body,omitempty"`
}

// NewMsgUnsendListOK creates MsgUnsendListOK with default headers values
func NewMsgUnsendListOK() *MsgUnsendListOK {
	return &MsgUnsendListOK{}
}

// WithPayload adds the payload to the msg unsend list o k response
func (o *MsgUnsendListOK) WithPayload(payload *models.InlineResponse20026) *MsgUnsendListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the msg unsend list o k response
func (o *MsgUnsendListOK) SetPayload(payload *models.InlineResponse20026) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MsgUnsendListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*MsgUnsendListDefault error

swagger:response msgUnsendListDefault
*/
type MsgUnsendListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMsgUnsendListDefault creates MsgUnsendListDefault with default headers values
func NewMsgUnsendListDefault(code int) *MsgUnsendListDefault {
	if code <= 0 {
		code = 500
	}

	return &MsgUnsendListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the msg unsend list default response
func (o *MsgUnsendListDefault) WithStatusCode(code int) *MsgUnsendListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the msg unsend list default response
func (o *MsgUnsendListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the msg unsend list default response
func (o *MsgUnsendListDefault) WithPayload(payload *models.Error) *MsgUnsendListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the msg unsend list default response
func (o *MsgUnsendListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MsgUnsendListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
