// Code generated by go-swagger; DO NOT EDIT.

package msg

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// MsgSendListOKCode is the HTTP code returned for type MsgSendListOK
const MsgSendListOKCode int = 200

/*MsgSendListOK 已发送消息列表

swagger:response msgSendListOK
*/
type MsgSendListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20026 `json:"body,omitempty"`
}

// NewMsgSendListOK creates MsgSendListOK with default headers values
func NewMsgSendListOK() *MsgSendListOK {
	return &MsgSendListOK{}
}

// WithPayload adds the payload to the msg send list o k response
func (o *MsgSendListOK) WithPayload(payload *models.InlineResponse20026) *MsgSendListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the msg send list o k response
func (o *MsgSendListOK) SetPayload(payload *models.InlineResponse20026) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MsgSendListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*MsgSendListDefault error

swagger:response msgSendListDefault
*/
type MsgSendListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMsgSendListDefault creates MsgSendListDefault with default headers values
func NewMsgSendListDefault(code int) *MsgSendListDefault {
	if code <= 0 {
		code = 500
	}

	return &MsgSendListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the msg send list default response
func (o *MsgSendListDefault) WithStatusCode(code int) *MsgSendListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the msg send list default response
func (o *MsgSendListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the msg send list default response
func (o *MsgSendListDefault) WithPayload(payload *models.Error) *MsgSendListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the msg send list default response
func (o *MsgSendListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MsgSendListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
