// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"log"
	"os"

	loads "github.com/go-openapi/loads"
	flags "github.com/jessevdk/go-flags"

	"youbite/restapi"
	"youbite/restapi/operations"
	_"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_"youbite/var"
	_"youbite/models"
	_"fmt"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {

	/*db,err := _var.OpenConnection()
	if err!=nil{
		fmt.Println(err.Error())
	}
	db.CreateTable(&models.Msg{})
	db.CreateTable(&models.Icon{})
	db.CreateTable(&models.Category{})
	db.CreateTable(&models.Member{})
	db.CreateTable(&models.Activity{})
	db.CreateTable(&models.ActivityTag{})
	db.CreateTable(&models.Banner{})
	db.CreateTable(&models.CategorySubCategory{})
	db.CreateTable(&models.Comment{})
	db.CreateTable(&models.Feedback{})
	db.CreateTable(&models.Order{})
	db.CreateTable(&models.Recharge{})*/

	//db.CreateTable(&models.UploadChapter{})

	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	api := operations.NewYoubiteAPI(swaggerSpec)
	server := restapi.NewServer(api)
	defer server.Shutdown()

	parser := flags.NewParser(server, flags.Default)
	parser.ShortDescription = "Youbite(Api)"
	parser.LongDescription = "Youbite(Api)"

	server.ConfigureFlags()
	for _, optsGroup := range api.CommandLineOptionsGroups {
		_, err := parser.AddGroup(optsGroup.ShortDescription, optsGroup.LongDescription, optsGroup.Options)
		if err != nil {
			log.Fatalln(err)
		}
	}

	if _, err := parser.Parse(); err != nil {
		code := 1
		if fe, ok := err.(*flags.Error); ok {
			if fe.Type == flags.ErrHelp {
				code = 0
			}
		}
		os.Exit(code)
	}

	server.ConfigureAPI()

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}
