// Code generated by go-swagger; DO NOT EDIT.

package feedback

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// FeedbackListOKCode is the HTTP code returned for type FeedbackListOK
const FeedbackListOKCode int = 200

/*FeedbackListOK 获取反馈列表

swagger:response feedbackListOK
*/
type FeedbackListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20020 `json:"body,omitempty"`
}

// NewFeedbackListOK creates FeedbackListOK with default headers values
func NewFeedbackListOK() *FeedbackListOK {
	return &FeedbackListOK{}
}

// WithPayload adds the payload to the feedback list o k response
func (o *FeedbackListOK) WithPayload(payload *models.InlineResponse20020) *FeedbackListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the feedback list o k response
func (o *FeedbackListOK) SetPayload(payload *models.InlineResponse20020) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FeedbackListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*FeedbackListDefault error

swagger:response feedbackListDefault
*/
type FeedbackListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFeedbackListDefault creates FeedbackListDefault with default headers values
func NewFeedbackListDefault(code int) *FeedbackListDefault {
	if code <= 0 {
		code = 500
	}

	return &FeedbackListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the feedback list default response
func (o *FeedbackListDefault) WithStatusCode(code int) *FeedbackListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the feedback list default response
func (o *FeedbackListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the feedback list default response
func (o *FeedbackListDefault) WithPayload(payload *models.Error) *FeedbackListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the feedback list default response
func (o *FeedbackListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FeedbackListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
