// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"crypto/tls"
	"net/http"

	errors "github.com/go-openapi/errors"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	graceful "github.com/tylerb/graceful"

	"youbite/restapi/operations"
	"youbite/restapi/operations/activity"
	"youbite/restapi/operations/banner"
	"youbite/restapi/operations/category"
	"youbite/restapi/operations/community"
	"youbite/restapi/operations/feedback"
	"youbite/restapi/operations/goods"
	"youbite/restapi/operations/member"
	"youbite/restapi/operations/msg"
	"youbite/restapi/operations/relation"
	"youbite/restapi/operations/report_err"
	"youbite/restapi/operations/shuoshuo"
	"youbite/restapi/operations/topic"
	"youbite/restapi/operations/upload"
)

// This file is safe to edit. Once it exists it will not be overwritten

//go:generate swagger generate server --target .. --name  --spec ../swagger.json

func configureFlags(api *operations.YoubiteAPI) {
	// api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroup{ ... }
}

func configureAPI(api *operations.YoubiteAPI) http.Handler {
	// configure the api here
	api.ServeError = errors.ServeError

	// Set your custom logger if needed. Default one is log.Printf
	// Expected interface func(string, ...interface{})
	//
	// Example:
	// api.Logger = log.Printf

	api.JSONConsumer = runtime.JSONConsumer()

	api.MultipartformConsumer = runtime.DiscardConsumer

	api.JSONProducer = runtime.JSONProducer()

	api.RelationNrCategorySubCategoryListRelationHandler = relation.NrCategorySubCategoryListRelationHandlerFunc(func(params relation.NrCategorySubCategoryListRelationParams) middleware.Responder {
		return middleware.NotImplemented("operation relation.NrCategorySubCategoryListRelation has not yet been implemented")
	})
	api.ActivityNrActivityDeleteHandler = activity.NrActivityDeleteHandlerFunc(func(params activity.NrActivityDeleteParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.NrActivityDelete has not yet been implemented")
	})
	api.ActivityNrActivityDetailHandler = activity.NrActivityDetailHandlerFunc(func(params activity.NrActivityDetailParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.NrActivityDetail has not yet been implemented")
	})
	api.ActivityNrActivityFavHandler = activity.NrActivityFavHandlerFunc(func(params activity.NrActivityFavParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.NrActivityFav has not yet been implemented")
	})
	api.ActivityNrActivityJoinHandler = activity.NrActivityJoinHandlerFunc(func(params activity.NrActivityJoinParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.NrActivityJoin has not yet been implemented")
	})
	api.ActivityNrActivityJoinedMemberListHandler = activity.NrActivityJoinedMemberListHandlerFunc(func(params activity.NrActivityJoinedMemberListParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.NrActivityJoinedMemberList has not yet been implemented")
	})
	api.ActivityNrActivityListHandler = activity.NrActivityListHandlerFunc(func(params activity.NrActivityListParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.NrActivityList has not yet been implemented")
	})
	api.ActivityNrActivityListFavHandler = activity.NrActivityListFavHandlerFunc(func(params activity.NrActivityListFavParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.NrActivityListFav has not yet been implemented")
	})
	api.ActivityNrActivityListJoinedHandler = activity.NrActivityListJoinedHandlerFunc(func(params activity.NrActivityListJoinedParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.NrActivityListJoined has not yet been implemented")
	})
	api.ActivityNrActivityListPraiseHandler = activity.NrActivityListPraiseHandlerFunc(func(params activity.NrActivityListPraiseParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.NrActivityListPraise has not yet been implemented")
	})
	api.ActivityNrActivityListSuggestHandler = activity.NrActivityListSuggestHandlerFunc(func(params activity.NrActivityListSuggestParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.NrActivityListSuggest has not yet been implemented")
	})
	api.ActivityNrActivityPraiseHandler = activity.NrActivityPraiseHandlerFunc(func(params activity.NrActivityPraiseParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.NrActivityPraise has not yet been implemented")
	})
	api.ActivityNrActivityTagDeleteHandler = activity.NrActivityTagDeleteHandlerFunc(func(params activity.NrActivityTagDeleteParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.NrActivityTagDelete has not yet been implemented")
	})
	api.ActivityNrActivityTagDetailHandler = activity.NrActivityTagDetailHandlerFunc(func(params activity.NrActivityTagDetailParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.NrActivityTagDetail has not yet been implemented")
	})
	api.ActivityNrActivityTagListHandler = activity.NrActivityTagListHandlerFunc(func(params activity.NrActivityTagListParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.NrActivityTagList has not yet been implemented")
	})
	api.CategoryNrCategoryListHandler = category.NrCategoryListHandlerFunc(func(params category.NrCategoryListParams) middleware.Responder {
		return middleware.NotImplemented("operation category.NrCategoryList has not yet been implemented")
	})
	api.CommunityNrCommunityDetailHandler = community.NrCommunityDetailHandlerFunc(func(params community.NrCommunityDetailParams) middleware.Responder {
		return middleware.NotImplemented("operation community.NrCommunityDetail has not yet been implemented")
	})
	api.GoodsNrGoodsSpecDetailHandler = goods.NrGoodsSpecDetailHandlerFunc(func(params goods.NrGoodsSpecDetailParams) middleware.Responder {
		return middleware.NotImplemented("operation goods.NrGoodsSpecDetail has not yet been implemented")
	})
	api.GoodsNrGoodsSpecListHandler = goods.NrGoodsSpecListHandlerFunc(func(params goods.NrGoodsSpecListParams) middleware.Responder {
		return middleware.NotImplemented("operation goods.NrGoodsSpecList has not yet been implemented")
	})
	api.MemberNrMemberAttentionListHandler = member.NrMemberAttentionListHandlerFunc(func(params member.NrMemberAttentionListParams) middleware.Responder {
		return middleware.NotImplemented("operation member.NrMemberAttentionList has not yet been implemented")
	})
	api.MemberNrMemberCheckRechargeHandler = member.NrMemberCheckRechargeHandlerFunc(func(params member.NrMemberCheckRechargeParams) middleware.Responder {
		return middleware.NotImplemented("operation member.NrMemberCheckRecharge has not yet been implemented")
	})
	api.MemberNrMemberDeleteHandler = member.NrMemberDeleteHandlerFunc(func(params member.NrMemberDeleteParams) middleware.Responder {
		return middleware.NotImplemented("operation member.NrMemberDelete has not yet been implemented")
	})
	api.MemberNrMemberEditHandler = member.NrMemberEditHandlerFunc(func(params member.NrMemberEditParams) middleware.Responder {
		return middleware.NotImplemented("operation member.NrMemberEdit has not yet been implemented")
	})
	api.MemberNrMemberFansListHandler = member.NrMemberFansListHandlerFunc(func(params member.NrMemberFansListParams) middleware.Responder {
		return middleware.NotImplemented("operation member.NrMemberFansList has not yet been implemented")
	})
	api.MemberNrMemberLoginByThirdPartyHandler = member.NrMemberLoginByThirdPartyHandlerFunc(func(params member.NrMemberLoginByThirdPartyParams) middleware.Responder {
		return middleware.NotImplemented("operation member.NrMemberLoginByThirdParty has not yet been implemented")
	})
	api.MemberNrMemberRegisterHandler = member.NrMemberRegisterHandlerFunc(func(params member.NrMemberRegisterParams) middleware.Responder {
		return middleware.NotImplemented("operation member.NrMemberRegister has not yet been implemented")
	})
	api.MemberNrMemberRegisterSendSmsHandler = member.NrMemberRegisterSendSmsHandlerFunc(func(params member.NrMemberRegisterSendSmsParams) middleware.Responder {
		return middleware.NotImplemented("operation member.NrMemberRegisterSendSms has not yet been implemented")
	})
	api.MemberNrMemberReportErrHandler = member.NrMemberReportErrHandlerFunc(func(params member.NrMemberReportErrParams) middleware.Responder {
		return middleware.NotImplemented("operation member.NrMemberReportErr has not yet been implemented")
	})
	api.MemberNrMemberScanCodeHandler = member.NrMemberScanCodeHandlerFunc(func(params member.NrMemberScanCodeParams) middleware.Responder {
		return middleware.NotImplemented("operation member.NrMemberScanCode has not yet been implemented")
	})
	api.MemberNrOrderSerialNuberHandler = member.NrOrderSerialNuberHandlerFunc(func(params member.NrOrderSerialNuberParams) middleware.Responder {
		return middleware.NotImplemented("operation member.NrOrderSerialNuber has not yet been implemented")
	})
	api.ShuoshuoNrShuoshuoCommentDetailHandler = shuoshuo.NrShuoshuoCommentDetailHandlerFunc(func(params shuoshuo.NrShuoshuoCommentDetailParams) middleware.Responder {
		return middleware.NotImplemented("operation shuoshuo.NrShuoshuoCommentDetail has not yet been implemented")
	})
	api.ShuoshuoNrShuoshuoCommentListHandler = shuoshuo.NrShuoshuoCommentListHandlerFunc(func(params shuoshuo.NrShuoshuoCommentListParams) middleware.Responder {
		return middleware.NotImplemented("operation shuoshuo.NrShuoshuoCommentList has not yet been implemented")
	})
	api.ShuoshuoNrShuoshuoDetailHandler = shuoshuo.NrShuoshuoDetailHandlerFunc(func(params shuoshuo.NrShuoshuoDetailParams) middleware.Responder {
		return middleware.NotImplemented("operation shuoshuo.NrShuoshuoDetail has not yet been implemented")
	})
	api.MemberNrStartUpHandler = member.NrStartUpHandlerFunc(func(params member.NrStartUpParams) middleware.Responder {
		return middleware.NotImplemented("operation member.NrStartUp has not yet been implemented")
	})
	api.RelationNrSubCategoryGoodsListRelationHandler = relation.NrSubCategoryGoodsListRelationHandlerFunc(func(params relation.NrSubCategoryGoodsListRelationParams) middleware.Responder {
		return middleware.NotImplemented("operation relation.NrSubCategoryGoodsListRelation has not yet been implemented")
	})
	api.TopicNrTopicDetailHandler = topic.NrTopicDetailHandlerFunc(func(params topic.NrTopicDetailParams) middleware.Responder {
		return middleware.NotImplemented("operation topic.NrTopicDetail has not yet been implemented")
	})
	api.ActivityActivityEditHandler = activity.ActivityEditHandlerFunc(func(params activity.ActivityEditParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.ActivityEdit has not yet been implemented")
	})
	api.ActivityActivityTagEditHandler = activity.ActivityTagEditHandlerFunc(func(params activity.ActivityTagEditParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.ActivityTagEdit has not yet been implemented")
	})
	api.ActivityActivityTagUploadHandler = activity.ActivityTagUploadHandlerFunc(func(params activity.ActivityTagUploadParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.ActivityTagUpload has not yet been implemented")
	})
	api.ActivityActivityUploadHandler = activity.ActivityUploadHandlerFunc(func(params activity.ActivityUploadParams) middleware.Responder {
		return middleware.NotImplemented("operation activity.ActivityUpload has not yet been implemented")
	})
	api.BannerBannerDetailHandler = banner.BannerDetailHandlerFunc(func(params banner.BannerDetailParams) middleware.Responder {
		return middleware.NotImplemented("operation banner.BannerDetail has not yet been implemented")
	})
	api.BannerBannerListHandler = banner.BannerListHandlerFunc(func(params banner.BannerListParams) middleware.Responder {
		return middleware.NotImplemented("operation banner.BannerList has not yet been implemented")
	})
	api.CategoryCategoryDetailHandler = category.CategoryDetailHandlerFunc(func(params category.CategoryDetailParams) middleware.Responder {
		return middleware.NotImplemented("operation category.CategoryDetail has not yet been implemented")
	})
	api.CommunityCommunityListHandler = community.CommunityListHandlerFunc(func(params community.CommunityListParams) middleware.Responder {
		return middleware.NotImplemented("operation community.CommunityList has not yet been implemented")
	})
	api.MemberFeedbackHandler = member.FeedbackHandlerFunc(func(params member.FeedbackParams) middleware.Responder {
		return middleware.NotImplemented("operation member.Feedback has not yet been implemented")
	})
	api.FeedbackFeedbackDetailHandler = feedback.FeedbackDetailHandlerFunc(func(params feedback.FeedbackDetailParams) middleware.Responder {
		return middleware.NotImplemented("operation feedback.FeedbackDetail has not yet been implemented")
	})
	api.FeedbackFeedbackListHandler = feedback.FeedbackListHandlerFunc(func(params feedback.FeedbackListParams) middleware.Responder {
		return middleware.NotImplemented("operation feedback.FeedbackList has not yet been implemented")
	})
	api.UploadFileUploadHandler = upload.FileUploadHandlerFunc(func(params upload.FileUploadParams) middleware.Responder {
		return middleware.NotImplemented("operation upload.FileUpload has not yet been implemented")
	})
	api.MemberFindPassEditPassHandler = member.FindPassEditPassHandlerFunc(func(params member.FindPassEditPassParams) middleware.Responder {
		return middleware.NotImplemented("operation member.FindPassEditPass has not yet been implemented")
	})
	api.MemberFindPassSendSmsHandler = member.FindPassSendSmsHandlerFunc(func(params member.FindPassSendSmsParams) middleware.Responder {
		return middleware.NotImplemented("operation member.FindPassSendSms has not yet been implemented")
	})
	api.GoodsGoodsDeleteHandler = goods.GoodsDeleteHandlerFunc(func(params goods.GoodsDeleteParams) middleware.Responder {
		return middleware.NotImplemented("operation goods.GoodsDelete has not yet been implemented")
	})
	api.GoodsGoodsDetailHandler = goods.GoodsDetailHandlerFunc(func(params goods.GoodsDetailParams) middleware.Responder {
		return middleware.NotImplemented("operation goods.GoodsDetail has not yet been implemented")
	})
	api.GoodsGoodsListHandler = goods.GoodsListHandlerFunc(func(params goods.GoodsListParams) middleware.Responder {
		return middleware.NotImplemented("operation goods.GoodsList has not yet been implemented")
	})
	api.MemberLoginHandler = member.LoginHandlerFunc(func(params member.LoginParams) middleware.Responder {
		return middleware.NotImplemented("operation member.Login has not yet been implemented")
	})
	api.MemberMemberDetailHandler = member.MemberDetailHandlerFunc(func(params member.MemberDetailParams) middleware.Responder {
		return middleware.NotImplemented("operation member.MemberDetail has not yet been implemented")
	})
	api.MemberMemberListHandler = member.MemberListHandlerFunc(func(params member.MemberListParams) middleware.Responder {
		return middleware.NotImplemented("operation member.MemberList has not yet been implemented")
	})
	api.MemberMemberOrderDetailHandler = member.MemberOrderDetailHandlerFunc(func(params member.MemberOrderDetailParams) middleware.Responder {
		return middleware.NotImplemented("operation member.MemberOrderDetail has not yet been implemented")
	})
	api.MemberMemberOrderListHandler = member.MemberOrderListHandlerFunc(func(params member.MemberOrderListParams) middleware.Responder {
		return middleware.NotImplemented("operation member.MemberOrderList has not yet been implemented")
	})
	api.MemberMemberRechargeListHandler = member.MemberRechargeListHandlerFunc(func(params member.MemberRechargeListParams) middleware.Responder {
		return middleware.NotImplemented("operation member.MemberRechargeList has not yet been implemented")
	})
	api.MsgMsgDetailHandler = msg.MsgDetailHandlerFunc(func(params msg.MsgDetailParams) middleware.Responder {
		return middleware.NotImplemented("operation msg.MsgDetail has not yet been implemented")
	})
	api.MsgMsgSendListHandler = msg.MsgSendListHandlerFunc(func(params msg.MsgSendListParams) middleware.Responder {
		return middleware.NotImplemented("operation msg.MsgSendList has not yet been implemented")
	})
	api.MsgMsgUnsendListHandler = msg.MsgUnsendListHandlerFunc(func(params msg.MsgUnsendListParams) middleware.Responder {
		return middleware.NotImplemented("operation msg.MsgUnsendList has not yet been implemented")
	})
	api.ReportErrReportErrDetailHandler = report_err.ReportErrDetailHandlerFunc(func(params report_err.ReportErrDetailParams) middleware.Responder {
		return middleware.NotImplemented("operation report_err.ReportErrDetail has not yet been implemented")
	})
	api.ReportErrReportErrListHandler = report_err.ReportErrListHandlerFunc(func(params report_err.ReportErrListParams) middleware.Responder {
		return middleware.NotImplemented("operation report_err.ReportErrList has not yet been implemented")
	})
	api.ShuoshuoShuoshuoListHandler = shuoshuo.ShuoshuoListHandlerFunc(func(params shuoshuo.ShuoshuoListParams) middleware.Responder {
		return middleware.NotImplemented("operation shuoshuo.ShuoshuoList has not yet been implemented")
	})
	api.TopicTopicListHandler = topic.TopicListHandlerFunc(func(params topic.TopicListParams) middleware.Responder {
		return middleware.NotImplemented("operation topic.TopicList has not yet been implemented")
	})

	api.ServerShutdown = func() {}

	return setupGlobalMiddleware(api.Serve(setupMiddlewares))
}

// The TLS configuration before HTTPS server starts.
func configureTLS(tlsConfig *tls.Config) {
	// Make all necessary changes to the TLS configuration here.
}

// As soon as server is initialized but not run yet, this function will be called.
// If you need to modify a config, store server instance to stop it individually later, this is the place.
// This function can be called multiple times, depending on the number of serving schemes.
// scheme value will be set accordingly: "http", "https" or "unix"
func configureServer(s *graceful.Server, scheme, addr string) {
}

// The middleware configuration is for the handler executors. These do not apply to the swagger.json document.
// The middleware executes after routing but before authentication, binding and validation
func setupMiddlewares(handler http.Handler) http.Handler {
	return handler
}

// The middleware configuration happens before anything, this middleware also applies to serving the swagger.json document.
// So this is a good place to plug in a panic handling middleware, logging and metrics
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return handler
}
