// Code generated by go-swagger; DO NOT EDIT.

package banner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// BannerDetailOKCode is the HTTP code returned for type BannerDetailOK
const BannerDetailOKCode int = 200

/*BannerDetailOK banner详情

swagger:response bannerDetailOK
*/
type BannerDetailOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20025 `json:"body,omitempty"`
}

// NewBannerDetailOK creates BannerDetailOK with default headers values
func NewBannerDetailOK() *BannerDetailOK {
	return &BannerDetailOK{}
}

// WithPayload adds the payload to the banner detail o k response
func (o *BannerDetailOK) WithPayload(payload *models.InlineResponse20025) *BannerDetailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the banner detail o k response
func (o *BannerDetailOK) SetPayload(payload *models.InlineResponse20025) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BannerDetailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*BannerDetailDefault error

swagger:response bannerDetailDefault
*/
type BannerDetailDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBannerDetailDefault creates BannerDetailDefault with default headers values
func NewBannerDetailDefault(code int) *BannerDetailDefault {
	if code <= 0 {
		code = 500
	}

	return &BannerDetailDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the banner detail default response
func (o *BannerDetailDefault) WithStatusCode(code int) *BannerDetailDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the banner detail default response
func (o *BannerDetailDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the banner detail default response
func (o *BannerDetailDefault) WithPayload(payload *models.Error) *BannerDetailDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the banner detail default response
func (o *BannerDetailDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BannerDetailDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
