// Code generated by go-swagger; DO NOT EDIT.

package report_err

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ReportErrListHandlerFunc turns a function with the right signature into a report err list handler
type ReportErrListHandlerFunc func(ReportErrListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ReportErrListHandlerFunc) Handle(params ReportErrListParams) middleware.Responder {
	return fn(params)
}

// ReportErrListHandler interface for that can handle valid report err list params
type ReportErrListHandler interface {
	Handle(ReportErrListParams) middleware.Responder
}

// NewReportErrList creates a new http.Handler for the report err list operation
func NewReportErrList(ctx *middleware.Context, handler ReportErrListHandler) *ReportErrList {
	return &ReportErrList{Context: ctx, Handler: handler}
}

/*ReportErrList swagger:route GET /reportErr/list reportErr reportErrList

报错列表

报错列表

*/
type ReportErrList struct {
	Context *middleware.Context
	Handler ReportErrListHandler
}

func (o *ReportErrList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReportErrListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
