// Code generated by go-swagger; DO NOT EDIT.

package report_err

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// ReportErrDetailOKCode is the HTTP code returned for type ReportErrDetailOK
const ReportErrDetailOKCode int = 200

/*ReportErrDetailOK 报错详情

swagger:response reportErrDetailOK
*/
type ReportErrDetailOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20023 `json:"body,omitempty"`
}

// NewReportErrDetailOK creates ReportErrDetailOK with default headers values
func NewReportErrDetailOK() *ReportErrDetailOK {
	return &ReportErrDetailOK{}
}

// WithPayload adds the payload to the report err detail o k response
func (o *ReportErrDetailOK) WithPayload(payload *models.InlineResponse20023) *ReportErrDetailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the report err detail o k response
func (o *ReportErrDetailOK) SetPayload(payload *models.InlineResponse20023) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReportErrDetailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ReportErrDetailDefault error

swagger:response reportErrDetailDefault
*/
type ReportErrDetailDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReportErrDetailDefault creates ReportErrDetailDefault with default headers values
func NewReportErrDetailDefault(code int) *ReportErrDetailDefault {
	if code <= 0 {
		code = 500
	}

	return &ReportErrDetailDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the report err detail default response
func (o *ReportErrDetailDefault) WithStatusCode(code int) *ReportErrDetailDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the report err detail default response
func (o *ReportErrDetailDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the report err detail default response
func (o *ReportErrDetailDefault) WithPayload(payload *models.Error) *ReportErrDetailDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the report err detail default response
func (o *ReportErrDetailDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReportErrDetailDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
