// Code generated by go-swagger; DO NOT EDIT.

package shuoshuo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// ShuoshuoCommentListOKCode is the HTTP code returned for type ShuoshuoCommentListOK
const ShuoshuoCommentListOKCode int = 200

/*ShuoshuoCommentListOK 获取反馈列表

swagger:response shuoshuoCommentListOK
*/
type ShuoshuoCommentListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2008 `json:"body,omitempty"`
}

// NewShuoshuoCommentListOK creates ShuoshuoCommentListOK with default headers values
func NewShuoshuoCommentListOK() *ShuoshuoCommentListOK {
	return &ShuoshuoCommentListOK{}
}

// WithPayload adds the payload to the shuoshuo comment list o k response
func (o *ShuoshuoCommentListOK) WithPayload(payload *models.InlineResponse2008) *ShuoshuoCommentListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the shuoshuo comment list o k response
func (o *ShuoshuoCommentListOK) SetPayload(payload *models.InlineResponse2008) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShuoshuoCommentListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrShuoshuoCommentListDefault error

swagger:response shuoshuoCommentListDefault
*/
type NrShuoshuoCommentListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrShuoshuoCommentListDefault creates NrShuoshuoCommentListDefault with default headers values
func NewNrShuoshuoCommentListDefault(code int) *NrShuoshuoCommentListDefault {
	if code <= 0 {
		code = 500
	}

	return &NrShuoshuoCommentListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the shuoshuo comment list default response
func (o *NrShuoshuoCommentListDefault) WithStatusCode(code int) *NrShuoshuoCommentListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the shuoshuo comment list default response
func (o *NrShuoshuoCommentListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the shuoshuo comment list default response
func (o *NrShuoshuoCommentListDefault) WithPayload(payload *models.Error) *NrShuoshuoCommentListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the shuoshuo comment list default response
func (o *NrShuoshuoCommentListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrShuoshuoCommentListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
