// Code generated by go-swagger; DO NOT EDIT.

package shuoshuo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrShuoshuoCommentListHandlerFunc turns a function with the right signature into a shuoshuo comment list handler
type NrShuoshuoCommentListHandlerFunc func(NrShuoshuoCommentListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrShuoshuoCommentListHandlerFunc) Handle(params NrShuoshuoCommentListParams) middleware.Responder {
	return fn(params)
}

// NrShuoshuoCommentListHandler interface for that can handle valid shuoshuo comment list params
type NrShuoshuoCommentListHandler interface {
	Handle(NrShuoshuoCommentListParams) middleware.Responder
}

// NewNrShuoshuoCommentList creates a new http.Handler for the shuoshuo comment list operation
func NewNrShuoshuoCommentList(ctx *middleware.Context, handler NrShuoshuoCommentListHandler) *NrShuoshuoCommentList {
	return &NrShuoshuoCommentList{Context: ctx, Handler: handler}
}

/*NrShuoshuoCommentList swagger:route GET /shuoshuo/comment/list Shuoshuo shuoshuoCommentList

获取说说下评论列表(含条件检索)

获取说说下评论列表(含条件检索)

*/
type NrShuoshuoCommentList struct {
	Context *middleware.Context
	Handler NrShuoshuoCommentListHandler
}

func (o *NrShuoshuoCommentList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrShuoshuoCommentListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
