// Code generated by go-swagger; DO NOT EDIT.

package shuoshuo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrShuoshuoCommentDetailHandlerFunc turns a function with the right signature into a shuoshuo comment detail handler
type NrShuoshuoCommentDetailHandlerFunc func(NrShuoshuoCommentDetailParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrShuoshuoCommentDetailHandlerFunc) Handle(params NrShuoshuoCommentDetailParams) middleware.Responder {
	return fn(params)
}

// NrShuoshuoCommentDetailHandler interface for that can handle valid shuoshuo comment detail params
type NrShuoshuoCommentDetailHandler interface {
	Handle(NrShuoshuoCommentDetailParams) middleware.Responder
}

// NewNrShuoshuoCommentDetail creates a new http.Handler for the shuoshuo comment detail operation
func NewNrShuoshuoCommentDetail(ctx *middleware.Context, handler NrShuoshuoCommentDetailHandler) *NrShuoshuoCommentDetail {
	return &NrShuoshuoCommentDetail{Context: ctx, Handler: handler}
}

/*NrShuoshuoCommentDetail swagger:route GET /shuoshuo/comment/detail Shuoshuo shuoshuoCommentDetail

说说下评论详情

说说下评论详情

*/
type NrShuoshuoCommentDetail struct {
	Context *middleware.Context
	Handler NrShuoshuoCommentDetailHandler
}

func (o *NrShuoshuoCommentDetail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrShuoshuoCommentDetailParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
