// Code generated by go-swagger; DO NOT EDIT.

package shuoshuo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ShuoshuoListHandlerFunc turns a function with the right signature into a shuoshuo list handler
type ShuoshuoListHandlerFunc func(ShuoshuoListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ShuoshuoListHandlerFunc) Handle(params ShuoshuoListParams) middleware.Responder {
	return fn(params)
}

// ShuoshuoListHandler interface for that can handle valid shuoshuo list params
type ShuoshuoListHandler interface {
	Handle(ShuoshuoListParams) middleware.Responder
}

// NewShuoshuoList creates a new http.Handler for the shuoshuo list operation
func NewShuoshuoList(ctx *middleware.Context, handler ShuoshuoListHandler) *ShuoshuoList {
	return &ShuoshuoList{Context: ctx, Handler: handler}
}

/*ShuoshuoList swagger:route GET /shuoshuo/list Shuoshuo shuoshuoList

获取说说列表(含条件检索)

获说说列表

*/
type ShuoshuoList struct {
	Context *middleware.Context
	Handler ShuoshuoListHandler
}

func (o *ShuoshuoList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewShuoshuoListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
