// Code generated by go-swagger; DO NOT EDIT.

package shuoshuo

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// ShuoshuoListOKCode is the HTTP code returned for type ShuoshuoListOK
const ShuoshuoListOKCode int = 200

/*ShuoshuoListOK 获取反馈列表

swagger:response shuoshuoListOK
*/
type ShuoshuoListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2008 `json:"body,omitempty"`
}

// NewShuoshuoListOK creates ShuoshuoListOK with default headers values
func NewShuoshuoListOK() *ShuoshuoListOK {
	return &ShuoshuoListOK{}
}

// WithPayload adds the payload to the shuoshuo list o k response
func (o *ShuoshuoListOK) WithPayload(payload *models.InlineResponse2008) *ShuoshuoListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the shuoshuo list o k response
func (o *ShuoshuoListOK) SetPayload(payload *models.InlineResponse2008) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShuoshuoListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ShuoshuoListDefault error

swagger:response shuoshuoListDefault
*/
type ShuoshuoListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewShuoshuoListDefault creates ShuoshuoListDefault with default headers values
func NewShuoshuoListDefault(code int) *ShuoshuoListDefault {
	if code <= 0 {
		code = 500
	}

	return &ShuoshuoListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the shuoshuo list default response
func (o *ShuoshuoListDefault) WithStatusCode(code int) *ShuoshuoListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the shuoshuo list default response
func (o *ShuoshuoListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the shuoshuo list default response
func (o *ShuoshuoListDefault) WithPayload(payload *models.Error) *ShuoshuoListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the shuoshuo list default response
func (o *ShuoshuoListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ShuoshuoListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
