// Code generated by go-swagger; DO NOT EDIT.

package goods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// GoodsListOKCode is the HTTP code returned for type GoodsListOK
const GoodsListOKCode int = 200

/*GoodsListOK 获取商品列表

swagger:response goodsListOK
*/
type GoodsListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20031 `json:"body,omitempty"`
}

// NewGoodsListOK creates GoodsListOK with default headers values
func NewGoodsListOK() *GoodsListOK {
	return &GoodsListOK{}
}

// WithPayload adds the payload to the goods list o k response
func (o *GoodsListOK) WithPayload(payload *models.InlineResponse20031) *GoodsListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the goods list o k response
func (o *GoodsListOK) SetPayload(payload *models.InlineResponse20031) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GoodsListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GoodsListDefault error

swagger:response goodsListDefault
*/
type GoodsListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGoodsListDefault creates GoodsListDefault with default headers values
func NewGoodsListDefault(code int) *GoodsListDefault {
	if code <= 0 {
		code = 500
	}

	return &GoodsListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the goods list default response
func (o *GoodsListDefault) WithStatusCode(code int) *GoodsListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the goods list default response
func (o *GoodsListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the goods list default response
func (o *GoodsListDefault) WithPayload(payload *models.Error) *GoodsListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the goods list default response
func (o *GoodsListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GoodsListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
