// Code generated by go-swagger; DO NOT EDIT.

package goods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// GoodsDeleteOKCode is the HTTP code returned for type GoodsDeleteOK
const GoodsDeleteOKCode int = 200

/*GoodsDeleteOK 商品详情

swagger:response goodsDeleteOK
*/
type GoodsDeleteOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2002 `json:"body,omitempty"`
}

// NewGoodsDeleteOK creates GoodsDeleteOK with default headers values
func NewGoodsDeleteOK() *GoodsDeleteOK {
	return &GoodsDeleteOK{}
}

// WithPayload adds the payload to the goods delete o k response
func (o *GoodsDeleteOK) WithPayload(payload *models.InlineResponse2002) *GoodsDeleteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the goods delete o k response
func (o *GoodsDeleteOK) SetPayload(payload *models.InlineResponse2002) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GoodsDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GoodsDeleteDefault error

swagger:response goodsDeleteDefault
*/
type GoodsDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGoodsDeleteDefault creates GoodsDeleteDefault with default headers values
func NewGoodsDeleteDefault(code int) *GoodsDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &GoodsDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the goods delete default response
func (o *GoodsDeleteDefault) WithStatusCode(code int) *GoodsDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the goods delete default response
func (o *GoodsDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the goods delete default response
func (o *GoodsDeleteDefault) WithPayload(payload *models.Error) *GoodsDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the goods delete default response
func (o *GoodsDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GoodsDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
