// Code generated by go-swagger; DO NOT EDIT.

package goods

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// GoodsDetailOKCode is the HTTP code returned for type GoodsDetailOK
const GoodsDetailOKCode int = 200

/*GoodsDetailOK 商品详情

swagger:response goodsDetailOK
*/
type GoodsDetailOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20030 `json:"body,omitempty"`
}

// NewGoodsDetailOK creates GoodsDetailOK with default headers values
func NewGoodsDetailOK() *GoodsDetailOK {
	return &GoodsDetailOK{}
}

// WithPayload adds the payload to the goods detail o k response
func (o *GoodsDetailOK) WithPayload(payload *models.InlineResponse20030) *GoodsDetailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the goods detail o k response
func (o *GoodsDetailOK) SetPayload(payload *models.InlineResponse20030) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GoodsDetailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GoodsDetailDefault error

swagger:response goodsDetailDefault
*/
type GoodsDetailDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGoodsDetailDefault creates GoodsDetailDefault with default headers values
func NewGoodsDetailDefault(code int) *GoodsDetailDefault {
	if code <= 0 {
		code = 500
	}

	return &GoodsDetailDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the goods detail default response
func (o *GoodsDetailDefault) WithStatusCode(code int) *GoodsDetailDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the goods detail default response
func (o *GoodsDetailDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the goods detail default response
func (o *GoodsDetailDefault) WithPayload(payload *models.Error) *GoodsDetailDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the goods detail default response
func (o *GoodsDetailDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GoodsDetailDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
