// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// FeedbackHandlerFunc turns a function with the right signature into a feedback handler
type FeedbackHandlerFunc func(FeedbackParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FeedbackHandlerFunc) Handle(params FeedbackParams) middleware.Responder {
	return fn(params)
}

// FeedbackHandler interface for that can handle valid feedback params
type FeedbackHandler interface {
	Handle(FeedbackParams) middleware.Responder
}

// NewFeedback creates a new http.Handler for the feedback operation
func NewFeedback(ctx *middleware.Context, handler FeedbackHandler) *Feedback {
	return &Feedback{Context: ctx, Handler: handler}
}

/*Feedback swagger:route POST /member/feedback Member feedback

反馈

反馈

*/
type Feedback struct {
	Context *middleware.Context
	Handler FeedbackHandler
}

func (o *Feedback) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFeedbackParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
