// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// FindPassSendSmsOKCode is the HTTP code returned for type FindPassSendSmsOK
const FindPassSendSmsOKCode int = 200

/*FindPassSendSmsOK 登录成功，返回登录信息

swagger:response findPassSendSmsOK
*/
type FindPassSendSmsOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2002 `json:"body,omitempty"`
}

// NewFindPassSendSmsOK creates FindPassSendSmsOK with default headers values
func NewFindPassSendSmsOK() *FindPassSendSmsOK {
	return &FindPassSendSmsOK{}
}

// WithPayload adds the payload to the find pass send sms o k response
func (o *FindPassSendSmsOK) WithPayload(payload *models.InlineResponse2002) *FindPassSendSmsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find pass send sms o k response
func (o *FindPassSendSmsOK) SetPayload(payload *models.InlineResponse2002) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindPassSendSmsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*FindPassSendSmsDefault error

swagger:response findPassSendSmsDefault
*/
type FindPassSendSmsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindPassSendSmsDefault creates FindPassSendSmsDefault with default headers values
func NewFindPassSendSmsDefault(code int) *FindPassSendSmsDefault {
	if code <= 0 {
		code = 500
	}

	return &FindPassSendSmsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find pass send sms default response
func (o *FindPassSendSmsDefault) WithStatusCode(code int) *FindPassSendSmsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find pass send sms default response
func (o *FindPassSendSmsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the find pass send sms default response
func (o *FindPassSendSmsDefault) WithPayload(payload *models.Error) *FindPassSendSmsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find pass send sms default response
func (o *FindPassSendSmsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindPassSendSmsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
