// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// MemberRechargeListOKCode is the HTTP code returned for type MemberRechargeListOK
const MemberRechargeListOKCode int = 200

/*MemberRechargeListOK 获取反馈列表

swagger:response memberRechargeListOK
*/
type MemberRechargeListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20015 `json:"body,omitempty"`
}

// NewMemberRechargeListOK creates MemberRechargeListOK with default headers values
func NewMemberRechargeListOK() *MemberRechargeListOK {
	return &MemberRechargeListOK{}
}

// WithPayload adds the payload to the member recharge list o k response
func (o *MemberRechargeListOK) WithPayload(payload *models.InlineResponse20015) *MemberRechargeListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the member recharge list o k response
func (o *MemberRechargeListOK) SetPayload(payload *models.InlineResponse20015) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MemberRechargeListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*MemberRechargeListDefault error

swagger:response memberRechargeListDefault
*/
type MemberRechargeListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMemberRechargeListDefault creates MemberRechargeListDefault with default headers values
func NewMemberRechargeListDefault(code int) *MemberRechargeListDefault {
	if code <= 0 {
		code = 500
	}

	return &MemberRechargeListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the member recharge list default response
func (o *MemberRechargeListDefault) WithStatusCode(code int) *MemberRechargeListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the member recharge list default response
func (o *MemberRechargeListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the member recharge list default response
func (o *MemberRechargeListDefault) WithPayload(payload *models.Error) *MemberRechargeListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the member recharge list default response
func (o *MemberRechargeListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MemberRechargeListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
