// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// MemberOrderDetailHandlerFunc turns a function with the right signature into a member order detail handler
type MemberOrderDetailHandlerFunc func(MemberOrderDetailParams) middleware.Responder

// Handle executing the request and returning a response
func (fn MemberOrderDetailHandlerFunc) Handle(params MemberOrderDetailParams) middleware.Responder {
	return fn(params)
}

// MemberOrderDetailHandler interface for that can handle valid member order detail params
type MemberOrderDetailHandler interface {
	Handle(MemberOrderDetailParams) middleware.Responder
}

// NewMemberOrderDetail creates a new http.Handler for the member order detail operation
func NewMemberOrderDetail(ctx *middleware.Context, handler MemberOrderDetailHandler) *MemberOrderDetail {
	return &MemberOrderDetail{Context: ctx, Handler: handler}
}

/*MemberOrderDetail swagger:route GET /member/order/detail Member memberOrderDetail

订单详情

订单详情

*/
type MemberOrderDetail struct {
	Context *middleware.Context
	Handler MemberOrderDetailHandler
}

func (o *MemberOrderDetail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewMemberOrderDetailParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
