// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// MemberOrderListOKCode is the HTTP code returned for type MemberOrderListOK
const MemberOrderListOKCode int = 200

/*MemberOrderListOK 获取反馈列表

swagger:response memberOrderListOK
*/
type MemberOrderListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20016 `json:"body,omitempty"`
}

// NewMemberOrderListOK creates MemberOrderListOK with default headers values
func NewMemberOrderListOK() *MemberOrderListOK {
	return &MemberOrderListOK{}
}

// WithPayload adds the payload to the member order list o k response
func (o *MemberOrderListOK) WithPayload(payload *models.InlineResponse20016) *MemberOrderListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the member order list o k response
func (o *MemberOrderListOK) SetPayload(payload *models.InlineResponse20016) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MemberOrderListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*MemberOrderListDefault error

swagger:response memberOrderListDefault
*/
type MemberOrderListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMemberOrderListDefault creates MemberOrderListDefault with default headers values
func NewMemberOrderListDefault(code int) *MemberOrderListDefault {
	if code <= 0 {
		code = 500
	}

	return &MemberOrderListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the member order list default response
func (o *MemberOrderListDefault) WithStatusCode(code int) *MemberOrderListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the member order list default response
func (o *MemberOrderListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the member order list default response
func (o *MemberOrderListDefault) WithPayload(payload *models.Error) *MemberOrderListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the member order list default response
func (o *MemberOrderListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MemberOrderListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
