// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// MemberListOKCode is the HTTP code returned for type MemberListOK
const MemberListOKCode int = 200

/*MemberListOK 获取反馈列表

swagger:response memberListOK
*/
type MemberListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2005 `json:"body,omitempty"`
}

// NewMemberListOK creates MemberListOK with default headers values
func NewMemberListOK() *MemberListOK {
	return &MemberListOK{}
}

// WithPayload adds the payload to the member list o k response
func (o *MemberListOK) WithPayload(payload *models.InlineResponse2005) *MemberListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the member list o k response
func (o *MemberListOK) SetPayload(payload *models.InlineResponse2005) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MemberListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*MemberListDefault error

swagger:response memberListDefault
*/
type MemberListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMemberListDefault creates MemberListDefault with default headers values
func NewMemberListDefault(code int) *MemberListDefault {
	if code <= 0 {
		code = 500
	}

	return &MemberListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the member list default response
func (o *MemberListDefault) WithStatusCode(code int) *MemberListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the member list default response
func (o *MemberListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the member list default response
func (o *MemberListDefault) WithPayload(payload *models.Error) *MemberListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the member list default response
func (o *MemberListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MemberListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
