// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrMemberRegisterHandlerFunc turns a function with the right signature into a member register handler
type NrMemberRegisterHandlerFunc func(NrMemberRegisterParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrMemberRegisterHandlerFunc) Handle(params NrMemberRegisterParams) middleware.Responder {
	return fn(params)
}

// NrMemberRegisterHandler interface for that can handle valid member register params
type NrMemberRegisterHandler interface {
	Handle(NrMemberRegisterParams) middleware.Responder
}

// NewNrMemberRegister creates a new http.Handler for the member register operation
func NewNrMemberRegister(ctx *middleware.Context, handler NrMemberRegisterHandler) *NrMemberRegister {
	return &NrMemberRegister{Context: ctx, Handler: handler}
}

/*NrMemberRegister swagger:route POST /member/register Member memberRegister

注册接口

注册接口

*/
type NrMemberRegister struct {
	Context *middleware.Context
	Handler NrMemberRegisterHandler
}

func (o *NrMemberRegister) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrMemberRegisterParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
