// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// MemberFansListOKCode is the HTTP code returned for type MemberFansListOK
const MemberFansListOKCode int = 200

/*MemberFansListOK 获取反馈列表

swagger:response memberFansListOK
*/
type MemberFansListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2005 `json:"body,omitempty"`
}

// NewMemberFansListOK creates MemberFansListOK with default headers values
func NewMemberFansListOK() *MemberFansListOK {
	return &MemberFansListOK{}
}

// WithPayload adds the payload to the member fans list o k response
func (o *MemberFansListOK) WithPayload(payload *models.InlineResponse2005) *MemberFansListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the member fans list o k response
func (o *MemberFansListOK) SetPayload(payload *models.InlineResponse2005) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MemberFansListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrMemberFansListDefault error

swagger:response memberFansListDefault
*/
type NrMemberFansListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrMemberFansListDefault creates NrMemberFansListDefault with default headers values
func NewNrMemberFansListDefault(code int) *NrMemberFansListDefault {
	if code <= 0 {
		code = 500
	}

	return &NrMemberFansListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the member fans list default response
func (o *NrMemberFansListDefault) WithStatusCode(code int) *NrMemberFansListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the member fans list default response
func (o *NrMemberFansListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the member fans list default response
func (o *NrMemberFansListDefault) WithPayload(payload *models.Error) *NrMemberFansListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the member fans list default response
func (o *NrMemberFansListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrMemberFansListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
