// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// MemberLoginByThirdPartyOKCode is the HTTP code returned for type MemberLoginByThirdPartyOK
const MemberLoginByThirdPartyOKCode int = 200

/*MemberLoginByThirdPartyOK 上报错误返回

swagger:response memberLoginByThirdPartyOK
*/
type MemberLoginByThirdPartyOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20014 `json:"body,omitempty"`
}

// NewMemberLoginByThirdPartyOK creates MemberLoginByThirdPartyOK with default headers values
func NewMemberLoginByThirdPartyOK() *MemberLoginByThirdPartyOK {
	return &MemberLoginByThirdPartyOK{}
}

// WithPayload adds the payload to the member login by third party o k response
func (o *MemberLoginByThirdPartyOK) WithPayload(payload *models.InlineResponse20014) *MemberLoginByThirdPartyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the member login by third party o k response
func (o *MemberLoginByThirdPartyOK) SetPayload(payload *models.InlineResponse20014) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MemberLoginByThirdPartyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrMemberLoginByThirdPartyDefault error

swagger:response memberLoginByThirdPartyDefault
*/
type NrMemberLoginByThirdPartyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrMemberLoginByThirdPartyDefault creates NrMemberLoginByThirdPartyDefault with default headers values
func NewNrMemberLoginByThirdPartyDefault(code int) *NrMemberLoginByThirdPartyDefault {
	if code <= 0 {
		code = 500
	}

	return &NrMemberLoginByThirdPartyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the member login by third party default response
func (o *NrMemberLoginByThirdPartyDefault) WithStatusCode(code int) *NrMemberLoginByThirdPartyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the member login by third party default response
func (o *NrMemberLoginByThirdPartyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the member login by third party default response
func (o *NrMemberLoginByThirdPartyDefault) WithPayload(payload *models.Error) *NrMemberLoginByThirdPartyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the member login by third party default response
func (o *NrMemberLoginByThirdPartyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrMemberLoginByThirdPartyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
