// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrMemberAttentionListHandlerFunc turns a function with the right signature into a member attention list handler
type NrMemberAttentionListHandlerFunc func(NrMemberAttentionListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrMemberAttentionListHandlerFunc) Handle(params NrMemberAttentionListParams) middleware.Responder {
	return fn(params)
}

// NrMemberAttentionListHandler interface for that can handle valid member attention list params
type NrMemberAttentionListHandler interface {
	Handle(NrMemberAttentionListParams) middleware.Responder
}

// NewNrMemberAttentionList creates a new http.Handler for the member attention list operation
func NewNrMemberAttentionList(ctx *middleware.Context, handler NrMemberAttentionListHandler) *NrMemberAttentionList {
	return &NrMemberAttentionList{Context: ctx, Handler: handler}
}

/*NrMemberAttentionList swagger:route GET /member/attention/list Member memberAttentionList

获取xx会员关注的人列表(含条件检索)

获取会员关注的人列表

*/
type NrMemberAttentionList struct {
	Context *middleware.Context
	Handler NrMemberAttentionListHandler
}

func (o *NrMemberAttentionList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrMemberAttentionListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
