// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrMemberDeleteHandlerFunc turns a function with the right signature into a member delete handler
type NrMemberDeleteHandlerFunc func(NrMemberDeleteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrMemberDeleteHandlerFunc) Handle(params NrMemberDeleteParams) middleware.Responder {
	return fn(params)
}

// NrMemberDeleteHandler interface for that can handle valid member delete params
type NrMemberDeleteHandler interface {
	Handle(NrMemberDeleteParams) middleware.Responder
}

// NewNrMemberDelete creates a new http.Handler for the member delete operation
func NewNrMemberDelete(ctx *middleware.Context, handler NrMemberDeleteHandler) *NrMemberDelete {
	return &NrMemberDelete{Context: ctx, Handler: handler}
}

/*NrMemberDelete swagger:route GET /member/delete Member memberDelete

冻结会员

冻结会员

*/
type NrMemberDelete struct {
	Context *middleware.Context
	Handler NrMemberDeleteHandler
}

func (o *NrMemberDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrMemberDeleteParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
