// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// OrderSerialNuberOKCode is the HTTP code returned for type OrderSerialNuberOK
const OrderSerialNuberOKCode int = 200

/*OrderSerialNuberOK 上报错误返回

swagger:response orderSerialNuberOK
*/
type OrderSerialNuberOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20014 `json:"body,omitempty"`
}

// NewOrderSerialNuberOK creates OrderSerialNuberOK with default headers values
func NewOrderSerialNuberOK() *OrderSerialNuberOK {
	return &OrderSerialNuberOK{}
}

// WithPayload adds the payload to the order serial nuber o k response
func (o *OrderSerialNuberOK) WithPayload(payload *models.InlineResponse20014) *OrderSerialNuberOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the order serial nuber o k response
func (o *OrderSerialNuberOK) SetPayload(payload *models.InlineResponse20014) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *OrderSerialNuberOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrOrderSerialNuberDefault error

swagger:response orderSerialNuberDefault
*/
type NrOrderSerialNuberDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrOrderSerialNuberDefault creates NrOrderSerialNuberDefault with default headers values
func NewNrOrderSerialNuberDefault(code int) *NrOrderSerialNuberDefault {
	if code <= 0 {
		code = 500
	}

	return &NrOrderSerialNuberDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the order serial nuber default response
func (o *NrOrderSerialNuberDefault) WithStatusCode(code int) *NrOrderSerialNuberDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the order serial nuber default response
func (o *NrOrderSerialNuberDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the order serial nuber default response
func (o *NrOrderSerialNuberDefault) WithPayload(payload *models.Error) *NrOrderSerialNuberDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the order serial nuber default response
func (o *NrOrderSerialNuberDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrOrderSerialNuberDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
