// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrOrderSerialNuberHandlerFunc turns a function with the right signature into a order serial nuber handler
type NrOrderSerialNuberHandlerFunc func(NrOrderSerialNuberParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrOrderSerialNuberHandlerFunc) Handle(params NrOrderSerialNuberParams) middleware.Responder {
	return fn(params)
}

// NrOrderSerialNuberHandler interface for that can handle valid order serial nuber params
type NrOrderSerialNuberHandler interface {
	Handle(NrOrderSerialNuberParams) middleware.Responder
}

// NewNrOrderSerialNuber creates a new http.Handler for the order serial nuber operation
func NewNrOrderSerialNuber(ctx *middleware.Context, handler NrOrderSerialNuberHandler) *NrOrderSerialNuber {
	return &NrOrderSerialNuber{Context: ctx, Handler: handler}
}

/*NrOrderSerialNuber swagger:route GET /member/order/serialNuber Member orderSerialNuber

充值订单产生流水号

充值订单产生流水号

*/
type NrOrderSerialNuber struct {
	Context *middleware.Context
	Handler NrOrderSerialNuberHandler
}

func (o *NrOrderSerialNuber) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrOrderSerialNuberParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
