// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ActivityTagUploadHandlerFunc turns a function with the right signature into a activity tag upload handler
type ActivityTagUploadHandlerFunc func(ActivityTagUploadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ActivityTagUploadHandlerFunc) Handle(params ActivityTagUploadParams) middleware.Responder {
	return fn(params)
}

// ActivityTagUploadHandler interface for that can handle valid activity tag upload params
type ActivityTagUploadHandler interface {
	Handle(ActivityTagUploadParams) middleware.Responder
}

// NewActivityTagUpload creates a new http.Handler for the activity tag upload operation
func NewActivityTagUpload(ctx *middleware.Context, handler ActivityTagUploadHandler) *ActivityTagUpload {
	return &ActivityTagUpload{Context: ctx, Handler: handler}
}

/*ActivityTagUpload swagger:route POST /activity/tag/upload Activity activityTagUpload

添加一个活动标签

*/
type ActivityTagUpload struct {
	Context *middleware.Context
	Handler ActivityTagUploadHandler
}

func (o *ActivityTagUpload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewActivityTagUploadParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
