// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// ActivityUploadOKCode is the HTTP code returned for type ActivityUploadOK
const ActivityUploadOKCode int = 200

/*ActivityUploadOK 添加活动成功，返回成功信息

swagger:response activityUploadOK
*/
type ActivityUploadOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2003 `json:"body,omitempty"`
}

// NewActivityUploadOK creates ActivityUploadOK with default headers values
func NewActivityUploadOK() *ActivityUploadOK {
	return &ActivityUploadOK{}
}

// WithPayload adds the payload to the activity upload o k response
func (o *ActivityUploadOK) WithPayload(payload *models.InlineResponse2003) *ActivityUploadOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity upload o k response
func (o *ActivityUploadOK) SetPayload(payload *models.InlineResponse2003) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActivityUploadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ActivityUploadDefault error

swagger:response activityUploadDefault
*/
type ActivityUploadDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewActivityUploadDefault creates ActivityUploadDefault with default headers values
func NewActivityUploadDefault(code int) *ActivityUploadDefault {
	if code <= 0 {
		code = 500
	}

	return &ActivityUploadDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the activity upload default response
func (o *ActivityUploadDefault) WithStatusCode(code int) *ActivityUploadDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the activity upload default response
func (o *ActivityUploadDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the activity upload default response
func (o *ActivityUploadDefault) WithPayload(payload *models.Error) *ActivityUploadDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity upload default response
func (o *ActivityUploadDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActivityUploadDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
