// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ActivityUploadHandlerFunc turns a function with the right signature into a activity upload handler
type ActivityUploadHandlerFunc func(ActivityUploadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ActivityUploadHandlerFunc) Handle(params ActivityUploadParams) middleware.Responder {
	return fn(params)
}

// ActivityUploadHandler interface for that can handle valid activity upload params
type ActivityUploadHandler interface {
	Handle(ActivityUploadParams) middleware.Responder
}

// NewActivityUpload creates a new http.Handler for the activity upload operation
func NewActivityUpload(ctx *middleware.Context, handler ActivityUploadHandler) *ActivityUpload {
	return &ActivityUpload{Context: ctx, Handler: handler}
}

/*ActivityUpload swagger:route POST /activity/upload Activity activityUpload

添加一个活动

*/
type ActivityUpload struct {
	Context *middleware.Context
	Handler ActivityUploadHandler
}

func (o *ActivityUpload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewActivityUploadParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
