// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ActivityTagEditHandlerFunc turns a function with the right signature into a activity tag edit handler
type ActivityTagEditHandlerFunc func(ActivityTagEditParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ActivityTagEditHandlerFunc) Handle(params ActivityTagEditParams) middleware.Responder {
	return fn(params)
}

// ActivityTagEditHandler interface for that can handle valid activity tag edit params
type ActivityTagEditHandler interface {
	Handle(ActivityTagEditParams) middleware.Responder
}

// NewActivityTagEdit creates a new http.Handler for the activity tag edit operation
func NewActivityTagEdit(ctx *middleware.Context, handler ActivityTagEditHandler) *ActivityTagEdit {
	return &ActivityTagEdit{Context: ctx, Handler: handler}
}

/*ActivityTagEdit swagger:route POST /activity/tag/edit Activity activityTagEdit

修改一个活动标签

*/
type ActivityTagEdit struct {
	Context *middleware.Context
	Handler ActivityTagEditHandler
}

func (o *ActivityTagEdit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewActivityTagEditParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
