// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrActivityListJoinedHandlerFunc turns a function with the right signature into a activity list joined handler
type NrActivityListJoinedHandlerFunc func(NrActivityListJoinedParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrActivityListJoinedHandlerFunc) Handle(params NrActivityListJoinedParams) middleware.Responder {
	return fn(params)
}

// NrActivityListJoinedHandler interface for that can handle valid activity list joined params
type NrActivityListJoinedHandler interface {
	Handle(NrActivityListJoinedParams) middleware.Responder
}

// NewNrActivityListJoined creates a new http.Handler for the activity list joined operation
func NewNrActivityListJoined(ctx *middleware.Context, handler NrActivityListJoinedHandler) *NrActivityListJoined {
	return &NrActivityListJoined{Context: ctx, Handler: handler}
}

/*NrActivityListJoined swagger:route GET /activity/list/joined Activity activityListJoined

获取参加的活动列表(含条件检索)

获取参加的活动列表(含条件检索)

*/
type NrActivityListJoined struct {
	Context *middleware.Context
	Handler NrActivityListJoinedHandler
}

func (o *NrActivityListJoined) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrActivityListJoinedParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
