// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// ActivityListSuggestOKCode is the HTTP code returned for type ActivityListSuggestOK
const ActivityListSuggestOKCode int = 200

/*ActivityListSuggestOK 获取反馈列表

swagger:response activityListSuggestOK
*/
type ActivityListSuggestOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewActivityListSuggestOK creates ActivityListSuggestOK with default headers values
func NewActivityListSuggestOK() *ActivityListSuggestOK {
	return &ActivityListSuggestOK{}
}

// WithPayload adds the payload to the activity list suggest o k response
func (o *ActivityListSuggestOK) WithPayload(payload *models.InlineResponse2004) *ActivityListSuggestOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity list suggest o k response
func (o *ActivityListSuggestOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActivityListSuggestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrActivityListSuggestDefault error

swagger:response activityListSuggestDefault
*/
type NrActivityListSuggestDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrActivityListSuggestDefault creates NrActivityListSuggestDefault with default headers values
func NewNrActivityListSuggestDefault(code int) *NrActivityListSuggestDefault {
	if code <= 0 {
		code = 500
	}

	return &NrActivityListSuggestDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the activity list suggest default response
func (o *NrActivityListSuggestDefault) WithStatusCode(code int) *NrActivityListSuggestDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the activity list suggest default response
func (o *NrActivityListSuggestDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the activity list suggest default response
func (o *NrActivityListSuggestDefault) WithPayload(payload *models.Error) *NrActivityListSuggestDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity list suggest default response
func (o *NrActivityListSuggestDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrActivityListSuggestDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
