// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// ActivityListOKCode is the HTTP code returned for type ActivityListOK
const ActivityListOKCode int = 200

/*ActivityListOK 获取反馈列表

swagger:response activityListOK
*/
type ActivityListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewActivityListOK creates ActivityListOK with default headers values
func NewActivityListOK() *ActivityListOK {
	return &ActivityListOK{}
}

// WithPayload adds the payload to the activity list o k response
func (o *ActivityListOK) WithPayload(payload *models.InlineResponse2004) *ActivityListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity list o k response
func (o *ActivityListOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActivityListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrActivityListDefault error

swagger:response activityListDefault
*/
type NrActivityListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrActivityListDefault creates NrActivityListDefault with default headers values
func NewNrActivityListDefault(code int) *NrActivityListDefault {
	if code <= 0 {
		code = 500
	}

	return &NrActivityListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the activity list default response
func (o *NrActivityListDefault) WithStatusCode(code int) *NrActivityListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the activity list default response
func (o *NrActivityListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the activity list default response
func (o *NrActivityListDefault) WithPayload(payload *models.Error) *NrActivityListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity list default response
func (o *NrActivityListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrActivityListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
