// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// ActivityJoinOKCode is the HTTP code returned for type ActivityJoinOK
const ActivityJoinOKCode int = 200

/*ActivityJoinOK 结果

swagger:response activityJoinOK
*/
type ActivityJoinOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2002 `json:"body,omitempty"`
}

// NewActivityJoinOK creates ActivityJoinOK with default headers values
func NewActivityJoinOK() *ActivityJoinOK {
	return &ActivityJoinOK{}
}

// WithPayload adds the payload to the activity join o k response
func (o *ActivityJoinOK) WithPayload(payload *models.InlineResponse2002) *ActivityJoinOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity join o k response
func (o *ActivityJoinOK) SetPayload(payload *models.InlineResponse2002) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActivityJoinOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrActivityJoinDefault error

swagger:response activityJoinDefault
*/
type NrActivityJoinDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrActivityJoinDefault creates NrActivityJoinDefault with default headers values
func NewNrActivityJoinDefault(code int) *NrActivityJoinDefault {
	if code <= 0 {
		code = 500
	}

	return &NrActivityJoinDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the activity join default response
func (o *NrActivityJoinDefault) WithStatusCode(code int) *NrActivityJoinDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the activity join default response
func (o *NrActivityJoinDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the activity join default response
func (o *NrActivityJoinDefault) WithPayload(payload *models.Error) *NrActivityJoinDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity join default response
func (o *NrActivityJoinDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrActivityJoinDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
