// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// ActivityDetailOKCode is the HTTP code returned for type ActivityDetailOK
const ActivityDetailOKCode int = 200

/*ActivityDetailOK 活动详情

swagger:response activityDetailOK
*/
type ActivityDetailOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2006 `json:"body,omitempty"`
}

// NewActivityDetailOK creates ActivityDetailOK with default headers values
func NewActivityDetailOK() *ActivityDetailOK {
	return &ActivityDetailOK{}
}

// WithPayload adds the payload to the activity detail o k response
func (o *ActivityDetailOK) WithPayload(payload *models.InlineResponse2006) *ActivityDetailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity detail o k response
func (o *ActivityDetailOK) SetPayload(payload *models.InlineResponse2006) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActivityDetailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrActivityDetailDefault error

swagger:response activityDetailDefault
*/
type NrActivityDetailDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrActivityDetailDefault creates NrActivityDetailDefault with default headers values
func NewNrActivityDetailDefault(code int) *NrActivityDetailDefault {
	if code <= 0 {
		code = 500
	}

	return &NrActivityDetailDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the activity detail default response
func (o *NrActivityDetailDefault) WithStatusCode(code int) *NrActivityDetailDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the activity detail default response
func (o *NrActivityDetailDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the activity detail default response
func (o *NrActivityDetailDefault) WithPayload(payload *models.Error) *NrActivityDetailDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity detail default response
func (o *NrActivityDetailDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrActivityDetailDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
