// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrActivityDetailHandlerFunc turns a function with the right signature into a activity detail handler
type NrActivityDetailHandlerFunc func(NrActivityDetailParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrActivityDetailHandlerFunc) Handle(params NrActivityDetailParams) middleware.Responder {
	return fn(params)
}

// NrActivityDetailHandler interface for that can handle valid activity detail params
type NrActivityDetailHandler interface {
	Handle(NrActivityDetailParams) middleware.Responder
}

// NewNrActivityDetail creates a new http.Handler for the activity detail operation
func NewNrActivityDetail(ctx *middleware.Context, handler NrActivityDetailHandler) *NrActivityDetail {
	return &NrActivityDetail{Context: ctx, Handler: handler}
}

/*NrActivityDetail swagger:route GET /activity/detail Activity activityDetail

活动详情

活动详情

*/
type NrActivityDetail struct {
	Context *middleware.Context
	Handler NrActivityDetailHandler
}

func (o *NrActivityDetail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrActivityDetailParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
