// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// ActivityListJoinedOKCode is the HTTP code returned for type ActivityListJoinedOK
const ActivityListJoinedOKCode int = 200

/*ActivityListJoinedOK 我参加的活动列表

swagger:response activityListJoinedOK
*/
type ActivityListJoinedOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewActivityListJoinedOK creates ActivityListJoinedOK with default headers values
func NewActivityListJoinedOK() *ActivityListJoinedOK {
	return &ActivityListJoinedOK{}
}

// WithPayload adds the payload to the activity list joined o k response
func (o *ActivityListJoinedOK) WithPayload(payload *models.InlineResponse2004) *ActivityListJoinedOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity list joined o k response
func (o *ActivityListJoinedOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActivityListJoinedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrActivityListJoinedDefault error

swagger:response activityListJoinedDefault
*/
type NrActivityListJoinedDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrActivityListJoinedDefault creates NrActivityListJoinedDefault with default headers values
func NewNrActivityListJoinedDefault(code int) *NrActivityListJoinedDefault {
	if code <= 0 {
		code = 500
	}

	return &NrActivityListJoinedDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the activity list joined default response
func (o *NrActivityListJoinedDefault) WithStatusCode(code int) *NrActivityListJoinedDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the activity list joined default response
func (o *NrActivityListJoinedDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the activity list joined default response
func (o *NrActivityListJoinedDefault) WithPayload(payload *models.Error) *NrActivityListJoinedDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity list joined default response
func (o *NrActivityListJoinedDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrActivityListJoinedDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
