// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// ActivityJoinedMemberListOKCode is the HTTP code returned for type ActivityJoinedMemberListOK
const ActivityJoinedMemberListOKCode int = 200

/*ActivityJoinedMemberListOK 活动报名会员列表

swagger:response activityJoinedMemberListOK
*/
type ActivityJoinedMemberListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2007 `json:"body,omitempty"`
}

// NewActivityJoinedMemberListOK creates ActivityJoinedMemberListOK with default headers values
func NewActivityJoinedMemberListOK() *ActivityJoinedMemberListOK {
	return &ActivityJoinedMemberListOK{}
}

// WithPayload adds the payload to the activity joined member list o k response
func (o *ActivityJoinedMemberListOK) WithPayload(payload *models.InlineResponse2007) *ActivityJoinedMemberListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity joined member list o k response
func (o *ActivityJoinedMemberListOK) SetPayload(payload *models.InlineResponse2007) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActivityJoinedMemberListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrActivityJoinedMemberListDefault error

swagger:response activityJoinedMemberListDefault
*/
type NrActivityJoinedMemberListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrActivityJoinedMemberListDefault creates NrActivityJoinedMemberListDefault with default headers values
func NewNrActivityJoinedMemberListDefault(code int) *NrActivityJoinedMemberListDefault {
	if code <= 0 {
		code = 500
	}

	return &NrActivityJoinedMemberListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the activity joined member list default response
func (o *NrActivityJoinedMemberListDefault) WithStatusCode(code int) *NrActivityJoinedMemberListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the activity joined member list default response
func (o *NrActivityJoinedMemberListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the activity joined member list default response
func (o *NrActivityJoinedMemberListDefault) WithPayload(payload *models.Error) *NrActivityJoinedMemberListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity joined member list default response
func (o *NrActivityJoinedMemberListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrActivityJoinedMemberListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
