// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrActivityListFavHandlerFunc turns a function with the right signature into a activity list fav handler
type NrActivityListFavHandlerFunc func(NrActivityListFavParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrActivityListFavHandlerFunc) Handle(params NrActivityListFavParams) middleware.Responder {
	return fn(params)
}

// NrActivityListFavHandler interface for that can handle valid activity list fav params
type NrActivityListFavHandler interface {
	Handle(NrActivityListFavParams) middleware.Responder
}

// NewNrActivityListFav creates a new http.Handler for the activity list fav operation
func NewNrActivityListFav(ctx *middleware.Context, handler NrActivityListFavHandler) *NrActivityListFav {
	return &NrActivityListFav{Context: ctx, Handler: handler}
}

/*NrActivityListFav swagger:route GET /activity/list/fav Activity activityListFav

获取收藏的活动列表(含条件检索)

获取收藏的活动列表(含条件检索)

*/
type NrActivityListFav struct {
	Context *middleware.Context
	Handler NrActivityListFavHandler
}

func (o *NrActivityListFav) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrActivityListFavParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
