// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrActivityTagListHandlerFunc turns a function with the right signature into a activity tag list handler
type NrActivityTagListHandlerFunc func(NrActivityTagListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrActivityTagListHandlerFunc) Handle(params NrActivityTagListParams) middleware.Responder {
	return fn(params)
}

// NrActivityTagListHandler interface for that can handle valid activity tag list params
type NrActivityTagListHandler interface {
	Handle(NrActivityTagListParams) middleware.Responder
}

// NewNrActivityTagList creates a new http.Handler for the activity tag list operation
func NewNrActivityTagList(ctx *middleware.Context, handler NrActivityTagListHandler) *NrActivityTagList {
	return &NrActivityTagList{Context: ctx, Handler: handler}
}

/*NrActivityTagList swagger:route GET /activity/tag/list Activity activityTagList

获取活动tag列表(含条件检索)

获取活动tag列表(含条件检索)

*/
type NrActivityTagList struct {
	Context *middleware.Context
	Handler NrActivityTagListHandler
}

func (o *NrActivityTagList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrActivityTagListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
