// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// ActivityListPraiseOKCode is the HTTP code returned for type ActivityListPraiseOK
const ActivityListPraiseOKCode int = 200

/*ActivityListPraiseOK 列表

swagger:response activityListPraiseOK
*/
type ActivityListPraiseOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2005 `json:"body,omitempty"`
}

// NewActivityListPraiseOK creates ActivityListPraiseOK with default headers values
func NewActivityListPraiseOK() *ActivityListPraiseOK {
	return &ActivityListPraiseOK{}
}

// WithPayload adds the payload to the activity list praise o k response
func (o *ActivityListPraiseOK) WithPayload(payload *models.InlineResponse2005) *ActivityListPraiseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity list praise o k response
func (o *ActivityListPraiseOK) SetPayload(payload *models.InlineResponse2005) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ActivityListPraiseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrActivityListPraiseDefault error

swagger:response activityListPraiseDefault
*/
type NrActivityListPraiseDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrActivityListPraiseDefault creates NrActivityListPraiseDefault with default headers values
func NewNrActivityListPraiseDefault(code int) *NrActivityListPraiseDefault {
	if code <= 0 {
		code = 500
	}

	return &NrActivityListPraiseDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the activity list praise default response
func (o *NrActivityListPraiseDefault) WithStatusCode(code int) *NrActivityListPraiseDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the activity list praise default response
func (o *NrActivityListPraiseDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the activity list praise default response
func (o *NrActivityListPraiseDefault) WithPayload(payload *models.Error) *NrActivityListPraiseDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the activity list praise default response
func (o *NrActivityListPraiseDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrActivityListPraiseDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
