// Code generated by go-swagger; DO NOT EDIT.

package activity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrActivityJoinHandlerFunc turns a function with the right signature into a activity join handler
type NrActivityJoinHandlerFunc func(NrActivityJoinParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrActivityJoinHandlerFunc) Handle(params NrActivityJoinParams) middleware.Responder {
	return fn(params)
}

// NrActivityJoinHandler interface for that can handle valid activity join params
type NrActivityJoinHandler interface {
	Handle(NrActivityJoinParams) middleware.Responder
}

// NewNrActivityJoin creates a new http.Handler for the activity join operation
func NewNrActivityJoin(ctx *middleware.Context, handler NrActivityJoinHandler) *NrActivityJoin {
	return &NrActivityJoin{Context: ctx, Handler: handler}
}

/*NrActivityJoin swagger:route GET /activity/join Activity activityJoin

参加活动

参加活动

*/
type NrActivityJoin struct {
	Context *middleware.Context
	Handler NrActivityJoinHandler
}

func (o *NrActivityJoin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrActivityJoinParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
