// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrCategoryListHandlerFunc turns a function with the right signature into a category list handler
type NrCategoryListHandlerFunc func(NrCategoryListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrCategoryListHandlerFunc) Handle(params NrCategoryListParams) middleware.Responder {
	return fn(params)
}

// NrCategoryListHandler interface for that can handle valid category list params
type NrCategoryListHandler interface {
	Handle(NrCategoryListParams) middleware.Responder
}

// NewNrCategoryList creates a new http.Handler for the category list operation
func NewNrCategoryList(ctx *middleware.Context, handler NrCategoryListHandler) *NrCategoryList {
	return &NrCategoryList{Context: ctx, Handler: handler}
}

/*NrCategoryList swagger:route GET /category/list Category categoryList

大类列表

大类列表

*/
type NrCategoryList struct {
	Context *middleware.Context
	Handler NrCategoryListHandler
}

func (o *NrCategoryList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrCategoryListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
