// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "youbite/models"
)

// CategoryListOKCode is the HTTP code returned for type CategoryListOK
const CategoryListOKCode int = 200

/*CategoryListOK 列表

swagger:response categoryListOK
*/
type CategoryListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20028 `json:"body,omitempty"`
}

// NewCategoryListOK creates CategoryListOK with default headers values
func NewCategoryListOK() *CategoryListOK {
	return &CategoryListOK{}
}

// WithPayload adds the payload to the category list o k response
func (o *CategoryListOK) WithPayload(payload *models.InlineResponse20028) *CategoryListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the category list o k response
func (o *CategoryListOK) SetPayload(payload *models.InlineResponse20028) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CategoryListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrCategoryListDefault error

swagger:response categoryListDefault
*/
type NrCategoryListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrCategoryListDefault creates NrCategoryListDefault with default headers values
func NewNrCategoryListDefault(code int) *NrCategoryListDefault {
	if code <= 0 {
		code = 500
	}

	return &NrCategoryListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the category list default response
func (o *NrCategoryListDefault) WithStatusCode(code int) *NrCategoryListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the category list default response
func (o *NrCategoryListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the category list default response
func (o *NrCategoryListDefault) WithPayload(payload *models.Error) *NrCategoryListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the category list default response
func (o *NrCategoryListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrCategoryListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
