// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Banner banner
// swagger:model Banner
type Banner struct {

	// cover
	Cover string `json:"cover,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// jumpid
	Jumpid int64 `json:"jumpid,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// type
	Type int64 `json:"type,omitempty"`

	// weburl
	Weburl string `json:"weburl,omitempty"`
}

// Validate validates this banner
func (m *Banner) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Banner) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Banner) UnmarshalBinary(b []byte) error {
	var res Banner
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
