// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InitDataExtraInfo init data extra info
// swagger:model InitData_extraInfo
type InitDataExtraInfo struct {

	// about us Url
	AboutUsURL string `json:"aboutUsUrl,omitempty"`

	// special Url
	SpecialURL string `json:"specialUrl,omitempty"`

	// version Url
	VersionURL string `json:"versionUrl,omitempty"`
}

// Validate validates this init data extra info
func (m *InitDataExtraInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *InitDataExtraInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InitDataExtraInfo) UnmarshalBinary(b []byte) error {
	var res InitDataExtraInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
