// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Msg msg
// swagger:model Msg
type Msg struct {

	// create time
	CreateTime int64 `json:"createTime,omitempty"`

	// from
	From int64 `json:"from,omitempty"`

	// sub title
	SubTitle string `json:"subTitle,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// to
	To int64 `json:"to,omitempty"`
}

// Validate validates this msg
func (m *Msg) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Msg) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Msg) UnmarshalBinary(b []byte) error {
	var res Msg
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
