// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Recharge 充值结果
// swagger:model Recharge
type Recharge struct {

	// 0=等待 1=成功 2=失败 3=其他
	Code int64 `json:"code,omitempty"`

	// member Id
	MemberID string `json:"memberId,omitempty"`

	// msg
	Msg string `json:"msg,omitempty"`

	// order no
	OrderNo string `json:"order_no,omitempty"`

	// 支付平台产生的流水号
	SerialNumber string `json:"serialNumber,omitempty"`

	// status
	Status int64 `json:"status,omitempty"`

	// time
	Time int64 `json:"time,omitempty"`

	// type
	Type int64 `json:"type,omitempty"`

	// value
	Value int64 `json:"value,omitempty"`
}

// Validate validates this recharge
func (m *Recharge) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Recharge) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Recharge) UnmarshalBinary(b []byte) error {
	var res Recharge
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
